proxy:
  #  ä»£ç†é…ç½®
  #  å›½å†…å¢™äº†gptçš„apiï¼Œæ‰€ä»¥å¾—ç”¨ä»£ç†ï¼Œä¸€èˆ¬ä½ ä½¿ç”¨çš„ä»£ç†è½¯ä»¶ä¼šæœ‰ç›¸å…³ä¿¡æ¯ï¼Œä¾‹å­ï¼š
  #  host: 127.0.0.1
  #  port: 7890
  #  è‹¥ä¸éœ€è¦ç•™ç©ºå³å¯
  host:
  port:

gpt:
  # å¦‚æœä½ ä½¿ç”¨äº†ç¬¬ä¸‰æ–¹GPT è¯·ä¿®æ”¹baseUrl
  # (OPENAIå®˜æ–¹åœ°å€ https://api.openai.com/)
  baseUrl: https://api.openai.com/
  # ä½¿ç”¨çš„ chat æ¨¡å‹ å¦‚gpt-3.5-turbo/gpt-4 (https://platform.openai.com/docs/models/models)
  model: gpt-3.5-turbo
  # æœ€å¤§tokené™åˆ¶ è¶Šå¤šçš„tokenæ„å‘³ç€è¶Šå¤šçš„èŠ±è´¹(gpt-3.5-turboä¸Šé™ä¸º4096token, gpt-4åˆ™ä¸º8192)
  maxToken: 2048
  # ä¿¡æ¯ç†µ è¶Šé«˜å›ç­”è¶Šéšæœº(Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.---via OPENAI)
  temperature: 0.5
  # æœ€å¤§è¯·æ±‚æ—¶é—´ è¶…æ—¶è‡ªåŠ¨ä¸­æ–­è¯·æ±‚
  ofSeconds: 10000
  # åŸºç¡€æé—® æ”¯æŒå¤šä¸ªæé—® å¯ç”¨æ¥è®¾å®šäººæ ¼(å¯¹åº”apiä¸­çš„systemè§’è‰²)
  basicPrompt:
    - "ç”¨ä¸­æ–‡å›ç­”æˆ‘çš„é—®é¢˜"
  #  openaiçš„apikey
  #  æ”¯æŒå¤šä¸ªkeyï¼ˆè™½ç„¶æœ‰åˆ¤ç©ºï¼Œä½†ä»ç„¶å»ºè®®æœ‰å¤šå°‘ä¸ªå†™å¤šå°‘ä¸ªï¼Œåˆ«ç•™ç©ºğŸ‘¨â€ğŸ”§ï¼‰
  apiKey:
    -
  # aiç”»å›¾
  # å›¾ç‰‡è´¨é‡ standard æˆ– hd
  imageQuality: standard
  # å›¾ç‰‡é£æ ¼ vivid æˆ– natural
  imageStyle: vivid
  # aiè¯­éŸ³
  # è¯­éŸ³æ¨¡å‹ tts-1 æˆ– tts-1-hd
  audioModel: tts-1
  # å£°éŸ³ alloy, echo, fable, onyx, nova, shimmer.
  audioVoice: alloy
  # é€Ÿåº¦ 0.25 åˆ° 4.0 ä¹‹é—´
  audioSpeed: 1.0
qq:
  #  æ˜¯å¦ä½¿ç”¨qq true/false
  enable: true
  #  qqè´¦å·
  account:
  #  æ˜¯å¦è‡ªåŠ¨åŒæ„å¥½å‹ç”³è¯·
  acceptNewFriend: false
  #  æ˜¯å¦è‡ªåŠ¨åŒæ„è¢«é‚€è¯·å…¥ç¾¤
  acceptNewGroup: false

wechat:
  #  æ˜¯å¦ä½¿ç”¨å¾®ä¿¡ true/false
  enable: false
  #  ç”Ÿæˆçš„ç™»å½•äºŒç»´ç è·¯å¾„ é»˜è®¤ä¸é¡¹ç›®åŒçº§
  qrPath: "./"

keyword:
  #  é‡ç½®ä¼šè¯æŒ‡ä»¤
  reset: "é‡ç½®ä¼šè¯"
  #  aiç”»å›¾æŒ‡ä»¤(DALLÂ·Eæ¨¡å‹ https://platform.openai.com/docs/models/dall-e)
  #  generation æ ¹æ®å…³é”®è¯ç”Ÿæˆå›¾ç‰‡(https://platform.openai.com/docs/guides/images/generations)
  image: "aiç”»å›¾"
  #  aiè¯­éŸ³æŒ‡ä»¤(TTSæ¨¡å‹ https://platform.openai.com/docs/api-reference/audio)
  audio: "aiè¯­éŸ³"
