proxy:
  #  代理配置
  #  国内墙了gpt的api，所以得用代理，一般你使用的代理软件会有相关信息，例子：
  #  host: 127.0.0.1
  #  port: 7890
  #  若不需要留空即可
  host:
  port:

chatgpt:
  #  openai的apikey
  #  支持多个key（虽然有判空，但仍然建议有多少个写多少个，别留空👨‍🔧）
  apiKey:
    - sk-xxxxx
    - sk-xxxxx

qq:
  #  是否使用qq true/false
  enable: true
  #  登陆方法：1.密码登录 2.扫码登录(推荐)
  method: 2
  #  qq账号密码
  account: 123456
  password: xxxx
  #  是否自动同意好友申请
  acceptNewFriend: false
  #  是否自动同意被邀请入群
  acceptNewGroup: false

wechat:
  #  是否使用微信 true/false
  enable: true
  #  生成的登录二维码路径 默认与项目同级
  qrPath: "./"
