proxy:
  #  ä»£ç†é…ç½®
  #  å›½å†…å¢™äº†gptçš„apiï¼Œæ‰€ä»¥å¾—ç”¨ä»£ç†ï¼Œä¸€èˆ¬ä½ ä½¿ç”¨çš„ä»£ç†è½¯ä»¶ä¼šæœ‰ç›¸å…³ä¿¡æ¯ï¼Œä¾‹å­ï¼š
  #  host: 127.0.0.1
  #  port: 7890
  #  è‹¥ä¸éœ€è¦ç•™ç©ºå³å¯
  host:
  port:

chatgpt:
  #  openaiçš„apikey
  #  æ”¯æŒå¤šä¸ªkeyï¼ˆè™½ç„¶æœ‰åˆ¤ç©ºï¼Œä½†ä»ç„¶å»ºè®®æœ‰å¤šå°‘ä¸ªå†™å¤šå°‘ä¸ªï¼Œåˆ«ç•™ç©ºğŸ‘¨â€ğŸ”§ï¼‰
  apiKey:
    - sk-xxxxx
    - sk-xxxxx

qq:
  #  æ˜¯å¦ä½¿ç”¨qq ture/false
  enable: true
  #  qqè´¦å·å¯†ç 
  account: 123456
  password: xxxx

wechat:
  #  æ˜¯å¦ä½¿ç”¨å¾®ä¿¡ ture/false
  enable: true
  #  ç”Ÿæˆçš„ç™»å½•äºŒç»´ç è·¯å¾„ é»˜è®¤ä¸é¡¹ç›®åŒçº§
  qrPath: "./"